<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Data_Cleaning_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('Cleaned_Hotel_Reservations.csv')

In [4]:
df.dtypes

Booking_ID                               object
no_of_adults                              int64
no_of_children                            int64
no_of_weekend_nights                      int64
no_of_week_nights                         int64
type_of_meal_plan                        object
room_type_reserved                       object
lead_time                                 int64
arrival_year                              int64
arrival_month                             int64
arrival_date                              int64
market_segment_type                      object
repeated_guest                            int64
no_of_previous_cancellations              int64
no_of_previous_bookings_not_canceled      int64
avg_price_per_room                      float64
no_of_special_requests                    int64
booking_status                            int64
arrival_date_full                        object
descriptive_room_type                    object
descriptive_meal_plan                    object
total_guests                              int64
total_nights                              int64
revenue_per_night                       float64
booking_segment                          object
dtype: object

In [5]:
df['arrival_date_full'] = pd.to_datetime(
    df['arrival_date_full'],
    format='%d-%m-%Y'
)

In [6]:
df['arrival_date_full'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
35550    False
35551    False
35552    False
35553    False
35554    False
Name: arrival_date_full, Length: 35555, dtype: bool

In [7]:
df = df.drop(columns=['Booking_ID'])

In [8]:
print("Final shape:", df.shape)
df.to_csv('Cleaned_Hotel_Reservations.csv', index=False)

Final shape: (35555, 24)