<a href="https://colab.research.google.com/github/jebin24it-boop/Infotact_Travel_Hospitality_Analytics/blob/Saurav-Data_Cleaning/notebooks/Data_Cleaning_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('Cleaned_Hotel_Reservations.csv')

In [4]:
df.dtypes

Booking_ID                               object
no_of_adults                              int64
no_of_children                            int64
no_of_weekend_nights                      int64
no_of_week_nights                         int64
type_of_meal_plan                        object
room_type_reserved                       object
lead_time                                 int64
arrival_year                              int64
arrival_month                             int64
arrival_date                              int64
market_segment_type                      object
repeated_guest                            int64
no_of_previous_cancellations              int64
no_of_previous_bookings_not_canceled      int64
avg_price_per_room                      float64
no_of_special_requests                    int64
booking_status                            int64
arrival_date_full                        object
descriptive_room_type                    object
descriptive_meal_plan                    object
total_guests                              int64
total_nights                              int64
revenue_per_night                       float64
booking_segment                          object
dtype: object

In [5]:
df['arrival_date_full'] = pd.to_datetime(
    df['arrival_date_full'],
    format='%d-%m-%Y'
)

In [6]:
df['arrival_date_full'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
35550    False
35551    False
35552    False
35553    False
35554    False
Name: arrival_date_full, Length: 35555, dtype: bool

In [7]:
df = df.drop(columns=['Booking_ID'])

In [ ]:
Q1 = df['avg_price_per_room'].quantile(0.25)
Q3 = df['avg_price_per_room'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df['avg_price_per_room'] >= lower) &
    (df['avg_price_per_room'] <= upper)
]

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,...,avg_price_per_room,no_of_special_requests,booking_status,arrival_date_full,descriptive_room_type,descriptive_meal_plan,total_guests,total_nights,revenue_per_night,booking_segment
0,2,0,1,2,0,0,224,2017,10,2,...,65.00,0,1,2017-10-02,4,2,2,3,21.666667,1
1,2,0,2,3,3,0,5,2018,11,6,...,106.68,1,1,2018-11-06,4,3,2,5,21.336000,0
2,1,0,2,1,0,0,1,2018,2,28,...,60.00,0,0,2018-02-28,4,2,1,3,20.000000,0
3,2,0,0,2,0,0,211,2018,5,20,...,100.00,0,0,2018-05-20,4,2,2,2,50.000000,1
4,2,0,1,1,3,0,48,2018,4,11,...,94.50,0,0,2018-04-11,4,3,2,2,47.250000,2

In [10]:
print("Final shape:", df.shape)
df.to_csv('Cleaned_Hotel_Reservations.csv', index=False)

Final shape: (35555, 24)